### ISSUE TITLE
能提供个带webview的demo吗

### ISSUE THREAD

**Issue by zmtzawqlp** [jaysonss/nested_inner_scroll_coordinator#1]
组件里面的demo，貌似直接用sliverlist不是更香吗？ demo没有体现组件的用处吧？能提供一个带webview的demo吗？ 谢谢

**Comment by huangyumeng123** [comment]
抱歉今天才看到，我加了一个webview demo到example项目里了

**Comment by huangyumeng123** [comment]
关于SliverList那个，我是复制粘贴的，用List当然也可以。。

**Comment by zmtzawqlp** [comment]
感谢，那个 _contentHeight/3 还是相当于写死了高度吧？ 这个应该判断下 viewport的高度吧？ 如果_contentHeight 大于viewport 这个高度设置成 viewport 的高度应该就行了吧？

**Comment by jaysonss** [comment]
是的，viewport的高度根据具体业务看，推荐不要大于screenHeight，否则在Android上可能会导致Crash
